<InfoFrame@BoxLayout>
    orientation: "vertical"
    row_force_default: True
    row_default_height: self.height//8
    
    PlayerData:
        id: player_1

    PlayerData:
        id: player_2

    PlayerData:
        id: player_3

    PlayerData:
        id: player_4

    PlayerData:
        id: player_5

    PlayerData:
        id: player_6

    PlayerData:
        id: player_7

    PlayerData:
        id: player_8