#:import Window kivy.core.window.Window

<PlayerInfo@GridLayout>:
    cols: 2

    Label:
        id: player_text
        name: 'player_text'

        text: '[b][color=#FF7F00]<Player Name>\n<IP Address>[/color][/b]'
        font_size: (Window.width**2 + Window.height**2) / 22**4
        markup: True
        halign: 'left'
        valign: 'middle'
        text_size: self.size

    PlayerIcon
        id: player_icon
        name: 'player_icon'

        