PROPERTY_INTERVAL = 0.082
CORNER_TO_PROPERTY_INTERVAL = 0.105
CORNER_OFFSET = 0.06
BORDER_OFFSET = 0.015

BOARD_SQUARE_LOCATIONS = {
    
    'GO': (CORNER_OFFSET, CORNER_OFFSET),
    
    'Br1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL),
    'Chest1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL),
    'Br2': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL),
    'ITax': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL),
    'RR1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL),
    'Lb1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL),
    'Chance1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL),
    'Lb2': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL),
    'Lb3': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL),
    
    'Jail': (CORNER_OFFSET, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    
    'Pk1': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Util1': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Pk2': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Pk3': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'RR2': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Or1': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Chest2': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Or2': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    'Or3': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),

    'Parking': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET)),

    'Rd1': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL)),
    'Chance2': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL)),
    'Rd2': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL)),
    'Rd3': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL)),
    'RR3': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL)),
    'Yl1': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL)),
    'Yl2': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL)),
    'Util2': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL)),
    'Yl3': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL)),
    
    'GO-TO-JAIL': (1 - (CORNER_OFFSET + BORDER_OFFSET), CORNER_OFFSET),

    'Gn1': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL), CORNER_OFFSET),
    'Gn2': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL), CORNER_OFFSET),
    'Chest3': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL), CORNER_OFFSET),
    'Gn3': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL), CORNER_OFFSET),
    'RR4': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL), CORNER_OFFSET),
    'Chance3': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL), CORNER_OFFSET),
    'Bl1': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL), CORNER_OFFSET),
    'LTax': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL), CORNER_OFFSET),
    'Bl2': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL), CORNER_OFFSET),
}

BOARD_SQUARE_COST = {

    'GO': None,
    
    'Br1': 60,
    'Chest1': None,
    'Br2': 60,
    'ITax': 200,
    'RR1': 200,
    'Lb1': 100,
    'Chance1': None,
    'Lb2': 100,
    'Lb3': 120,
    
    'Jail': None,
    
    'Pk1': 140,
    'Util1': 150,
    'Pk2': 140,
    'Pk3': 160,
    'RR2': 200,
    'Or1': 180,
    'Chest2': None,
    'Or2': 180,
    'Or3': 200,

    'Parking': None,

    'Rd1': 220,
    'Chance2': None,
    'Rd2': 220,
    'Rd3': 240,
    'RR3': 200,
    'Yl1': 260,
    'Yl2': 260,
    'Util2': None,
    'Yl3': 280,
    
    'GO-TO-JAIL': None,

    'Gn1': 300,
    'Gn2': 300,
    'Chest3': None,
    'Gn3': 320,
    'RR4': 200,
    'Chance3': None,
    'Bl1': 350,
    'LTax': 100,
    'Bl2': 400,
}