PROPERTY_INTERVAL = 0.082
CORNER_TO_PROPERTY_INTERVAL = 0.105
CORNER_OFFSET = 0.06
BORDER_OFFSET = 0.015

BOARD_LOCATIONS = {
    'Corners': {
        'GO': (CORNER_OFFSET, CORNER_OFFSET),
        'Jail': (CORNER_OFFSET, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Parking': (1 - CORNER_OFFSET, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'GO-TO-JAIL': (1 - (CORNER_OFFSET + BORDER_OFFSET), CORNER_OFFSET)
    },
    'Line1': {
        'Br1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL),
        'Chest': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL),
        'Br2': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL),
        'Tax': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL),
        'RR': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL),
        'Lb1': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL),
        'Chance': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL),
        'Lb2': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL),
        'Lb3': (CORNER_OFFSET, CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL),
    },
    'Line2': {
        'Pk1': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Util': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Pk2': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Pk3': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'RR': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Or1': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Chest': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Or2': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
        'Or3': (CORNER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL, 1 - (CORNER_OFFSET + BORDER_OFFSET)),
    },
    'Line3': {
        'Rd1': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL)),
        'Chance': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL)),
        'Rd2': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL)),
        'Rd3': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL)),
        'RR': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL)),
        'Yl1': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL)),
        'Yl2': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL)),
        'Util': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL)),
        'Yl3': (1 - (CORNER_OFFSET + BORDER_OFFSET), 1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL)),
    },
    'Line4': {
        'Gn1': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL), CORNER_OFFSET),
        'Gn2': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + PROPERTY_INTERVAL), CORNER_OFFSET),
        'Chest': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 2*PROPERTY_INTERVAL), CORNER_OFFSET),
        'Gn3': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 3*PROPERTY_INTERVAL), CORNER_OFFSET),
        'RR': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 4*PROPERTY_INTERVAL), CORNER_OFFSET),
        'Chance': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 5*PROPERTY_INTERVAL), CORNER_OFFSET),
        'Bl1': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 6*PROPERTY_INTERVAL), CORNER_OFFSET),
        'Tax': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 7*PROPERTY_INTERVAL), CORNER_OFFSET),
        'Bl2': (1 - (CORNER_OFFSET + BORDER_OFFSET + CORNER_TO_PROPERTY_INTERVAL + 8*PROPERTY_INTERVAL), CORNER_OFFSET),
    }
}